name: CoderCo Custom Action CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run custom greeting action
        uses: ArmaanKay/coderco-custom@main
        with:
          who-to-greet: 'CoderCo Team'
